"""Complete nmap flag catalogue sourced from the official man page.

Each entry: (flag_template, natural-language description, category-tag).
The flag template may contain {target} or a placeholder value for training.
"""
from __future__ import annotations

FLAGS: list[tuple[str, str, str]] = [
    # --- target specification ---
    ("nmap {target}", "default scan of a target host or network", "basic"),
    ("nmap -iL targets.txt", "read target list from a file", "basic"),
    ("nmap -iR 1000", "pick 1000 random internet targets", "basic"),
    ("nmap --exclude 10.0.0.1,10.0.0.2 {target}", "exclude specific hosts from the scan", "basic"),
    ("nmap --excludefile exclude.txt {target}", "exclude hosts listed in a file", "basic"),

    # --- host discovery ---
    ("nmap -sL {target}", "list scan - no probes sent to targets", "discovery"),
    ("nmap -sn {target}", "ping scan - disable port scan", "discovery"),
    ("nmap -Pn {target}", "skip host discovery treat all hosts as up", "discovery"),
    ("nmap -PS22,80,443 {target}", "tcp syn ping discovery", "discovery"),
    ("nmap -PA80,443 {target}", "tcp ack ping discovery", "discovery"),
    ("nmap -PU53,161 {target}", "udp ping discovery", "discovery"),
    ("nmap -PY {target}", "sctp init ping discovery", "discovery"),
    ("nmap -PE {target}", "icmp echo ping", "discovery"),
    ("nmap -PP {target}", "icmp timestamp ping", "discovery"),
    ("nmap -PM {target}", "icmp netmask ping", "discovery"),
    ("nmap -PO {target}", "ip protocol ping", "discovery"),
    ("nmap -PR {target}", "arp ping discovery on local network", "discovery"),
    ("nmap --disable-arp-ping {target}", "disable arp ping on local segments", "discovery"),
    ("nmap --traceroute {target}", "trace hop path to target", "discovery"),
    ("nmap -n {target}", "skip reverse dns resolution", "discovery"),
    ("nmap -R {target}", "always resolve reverse dns", "discovery"),
    ("nmap --dns-servers 8.8.8.8,1.1.1.1 {target}", "specify custom dns resolvers", "discovery"),
    ("nmap --system-dns {target}", "use the system dns resolver", "discovery"),
    ("nmap --resolve-all {target}", "resolve all addresses for each host", "discovery"),

    # --- scan techniques ---
    ("nmap -sS {target}", "tcp syn stealth scan half-open", "technique"),
    ("nmap -sT {target}", "tcp connect scan full three-way handshake", "technique"),
    ("nmap -sU {target}", "udp port scan", "technique"),
    ("nmap -sA {target}", "tcp ack scan map firewall rules", "technique"),
    ("nmap -sW {target}", "tcp window scan", "technique"),
    ("nmap -sM {target}", "tcp maimon scan", "technique"),
    ("nmap -sN {target}", "tcp null scan no flags", "technique"),
    ("nmap -sF {target}", "tcp fin scan", "technique"),
    ("nmap -sX {target}", "tcp xmas scan fin psh urg", "technique"),
    ("nmap --scanflags URGACKPSHRSTSYNFIN {target}", "custom tcp flags scan", "technique"),
    ("nmap -sI zombie.example.com {target}", "tcp idle zombie scan for anonymity", "technique"),
    ("nmap -sY {target}", "sctp init scan", "technique"),
    ("nmap -sZ {target}", "sctp cookie echo scan", "technique"),
    ("nmap -sO {target}", "ip protocol scan", "technique"),
    ("nmap -b ftp.example.com {target}", "ftp bounce attack scan", "technique"),

    # --- port specification ---
    ("nmap -p 80 {target}", "scan a single tcp port", "ports"),
    ("nmap -p 1-1000 {target}", "scan a port range", "ports"),
    ("nmap -p- {target}", "scan all 65535 tcp ports", "ports"),
    ("nmap -p T:80,443,U:53,161 {target}", "scan both tcp and udp explicit ports", "ports"),
    ("nmap -p http,https,ssh {target}", "scan by service name", "ports"),
    ("nmap -F {target}", "fast scan top 100 ports", "ports"),
    ("nmap --top-ports 20 {target}", "scan the 20 most common ports", "ports"),
    ("nmap --top-ports 1000 {target}", "scan the 1000 most common ports", "ports"),
    ("nmap --port-ratio 0.7 {target}", "scan ports more common than given ratio", "ports"),
    ("nmap -r {target}", "scan ports sequentially not randomized", "ports"),

    # --- service / os ---
    ("nmap -sV {target}", "service version detection", "service"),
    ("nmap -sV --version-intensity 9 {target}", "maximum version detection intensity", "service"),
    ("nmap -sV --version-light {target}", "light version scan fast", "service"),
    ("nmap -sV --version-all {target}", "try every probe for version detection", "service"),
    ("nmap -sV --version-trace {target}", "debug version detection", "service"),
    ("nmap -O {target}", "os fingerprint detection", "os"),
    ("nmap -O --osscan-limit {target}", "only try os detection against promising hosts", "os"),
    ("nmap -O --osscan-guess {target}", "guess os aggressively", "os"),
    ("nmap --max-os-tries 1 {target}", "limit os detection retries", "os"),
    ("nmap -A {target}", "aggressive scan os service scripts traceroute", "aggressive"),

    # --- nse scripting ---
    ("nmap -sC {target}", "run default nse scripts", "scripts"),
    ("nmap --script default {target}", "explicitly run default category", "scripts"),
    ("nmap --script vuln {target}", "run vulnerability detection scripts", "scripts"),
    ("nmap --script safe {target}", "run only non-intrusive safe scripts", "scripts"),
    ("nmap --script intrusive {target}", "run intrusive scripts", "scripts"),
    ("nmap --script discovery {target}", "run discovery scripts", "scripts"),
    ("nmap --script auth {target}", "run auth-related scripts", "scripts"),
    ("nmap --script brute {target}", "run brute force scripts", "scripts"),
    ("nmap --script exploit {target}", "run exploit scripts", "scripts"),
    ("nmap --script fuzzer {target}", "run fuzzing scripts", "scripts"),
    ("nmap --script malware {target}", "run malware detection scripts", "scripts"),
    ("nmap --script dos {target}", "run denial of service scripts", "scripts"),
    ("nmap --script broadcast {target}", "run broadcast scripts", "scripts"),
    ("nmap --script external {target}", "run scripts that query external services", "scripts"),
    ("nmap --script version {target}", "run version category scripts", "scripts"),
    ("nmap --script 'http-*' {target}", "run all scripts whose name starts with http", "scripts"),
    ("nmap --script 'not intrusive' {target}", "run all non-intrusive scripts", "scripts"),
    ("nmap --script-args user=admin,pass=password {target}", "pass arguments to scripts", "scripts"),
    ("nmap --script-args-file args.txt {target}", "load script arguments from a file", "scripts"),
    ("nmap --script-help all {target}", "show help for nse scripts", "scripts"),
    ("nmap --script-trace {target}", "show incoming and outgoing script communication", "scripts"),
    ("nmap --script-updatedb {target}", "update the nse script database", "scripts"),

    # --- timing and performance ---
    ("nmap -T0 {target}", "paranoid timing ids evasion very slow", "timing"),
    ("nmap -T1 {target}", "sneaky timing slow", "timing"),
    ("nmap -T2 {target}", "polite timing reduces bandwidth", "timing"),
    ("nmap -T3 {target}", "normal timing default", "timing"),
    ("nmap -T4 {target}", "aggressive timing fast", "timing"),
    ("nmap -T5 {target}", "insane timing fastest", "timing"),
    ("nmap --min-hostgroup 50 {target}", "minimum parallel host group size", "timing"),
    ("nmap --max-hostgroup 100 {target}", "maximum parallel host group size", "timing"),
    ("nmap --min-parallelism 10 {target}", "minimum probe parallelism", "timing"),
    ("nmap --max-parallelism 100 {target}", "maximum probe parallelism", "timing"),
    ("nmap --min-rtt-timeout 100ms {target}", "minimum probe round trip time", "timing"),
    ("nmap --max-rtt-timeout 500ms {target}", "maximum probe round trip time", "timing"),
    ("nmap --initial-rtt-timeout 200ms {target}", "initial probe round trip time", "timing"),
    ("nmap --max-retries 2 {target}", "maximum retransmissions", "timing"),
    ("nmap --host-timeout 30m {target}", "give up on a host after duration", "timing"),
    ("nmap --scan-delay 1s {target}", "delay between probes to a host", "timing"),
    ("nmap --max-scan-delay 10s {target}", "cap on scan delay", "timing"),
    ("nmap --min-rate 1000 {target}", "send packets at minimum rate per second", "timing"),
    ("nmap --max-rate 100 {target}", "send packets at maximum rate per second", "timing"),
    ("nmap --defeat-rst-ratelimit {target}", "ignore rst packet rate limiting", "timing"),
    ("nmap --defeat-icmp-ratelimit {target}", "ignore icmp rate limiting", "timing"),
    ("nmap --nsock-engine epoll {target}", "force a specific nsock io engine", "timing"),

    # --- firewall / ids evasion ---
    ("nmap -f {target}", "fragment probe packets", "evasion"),
    ("nmap --mtu 16 {target}", "set custom fragment size mtu", "evasion"),
    ("nmap -D RND:10 {target}", "use decoy scan with random decoys", "evasion"),
    ("nmap -S spoof.example.com {target}", "spoof source ip address", "evasion"),
    ("nmap -e eth0 {target}", "use a specific network interface", "evasion"),
    ("nmap -g 53 {target}", "use a fixed source port", "evasion"),
    ("nmap --source-port 53 {target}", "use a fixed source port alternate form", "evasion"),
    ("nmap --proxies http://proxy:8080 {target}", "relay connections through http or socks proxies", "evasion"),
    ("nmap --data AA55 {target}", "append custom hex payload", "evasion"),
    ("nmap --data-string 'hello' {target}", "append custom ascii payload", "evasion"),
    ("nmap --data-length 25 {target}", "append random data of length", "evasion"),
    ("nmap --ip-options 'L 10.0.0.1' {target}", "send packets with specified ip options", "evasion"),
    ("nmap --ttl 64 {target}", "set ip time to live", "evasion"),
    ("nmap --randomize-hosts {target}", "randomize target scan order", "evasion"),
    ("nmap --spoof-mac 0 {target}", "spoof mac address random", "evasion"),
    ("nmap --spoof-mac Apple {target}", "spoof mac address of a vendor", "evasion"),
    ("nmap --badsum {target}", "send packets with bogus tcp or udp checksum", "evasion"),
    ("nmap --adler32 {target}", "use deprecated adler32 sctp checksums", "evasion"),

    # --- output ---
    ("nmap -oN scan.txt {target}", "normal human readable output to file", "output"),
    ("nmap -oX scan.xml {target}", "xml output to file", "output"),
    ("nmap -oS scan.skiddy {target}", "script kiddie output", "output"),
    ("nmap -oG scan.gnmap {target}", "grepable output", "output"),
    ("nmap -oA scan {target}", "all output formats at once", "output"),
    ("nmap -v {target}", "verbose output", "output"),
    ("nmap -vv {target}", "very verbose output", "output"),
    ("nmap -d {target}", "debug output", "output"),
    ("nmap -dd {target}", "extra debug output", "output"),
    ("nmap --reason {target}", "show reason ports are in a given state", "output"),
    ("nmap --open {target}", "only show open ports", "output"),
    ("nmap --packet-trace {target}", "show all sent and received packets", "output"),
    ("nmap --iflist {target}", "list interfaces and routes", "output"),
    ("nmap --append-output {target}", "append rather than clobber output files", "output"),
    ("nmap --resume scan.txt", "resume an aborted scan", "output"),
    ("nmap --stylesheet default.xsl {target}", "apply xsl stylesheet to xml", "output"),
    ("nmap --webxml {target}", "reference portable nmap xsl online", "output"),
    ("nmap --no-stylesheet {target}", "prevent xml referencing stylesheet", "output"),

    # --- misc ---
    ("nmap -6 {target}", "ipv6 target scan", "misc"),
    ("nmap -A -T4 {target}", "aggressive with fast timing", "misc"),
    ("nmap --datadir /opt/nmap-data {target}", "override nmap data files location", "misc"),
    ("nmap --send-eth {target}", "force raw ethernet transmission", "misc"),
    ("nmap --send-ip {target}", "force raw ip transmission", "misc"),
    ("nmap --privileged {target}", "assume the user has raw socket privileges", "misc"),
    ("nmap --unprivileged {target}", "assume no privileged operations", "misc"),
    ("nmap -V", "print nmap version", "misc"),
    ("nmap -h", "print help summary", "misc"),
]
